name: Test artifacts

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - run: mkdir -p ./build

      - run: cd build

      - run: echo "Hello world" > hello.txt

      - run: ls build
