name: Test artifacts

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: ls ${{ github.workspace }}
      
      - run: |
          mkdir -p build
          cd build
          echo "Hello world" > hello.txt
          ls
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./build

  job2:
    runs-on: ubuntu-latest

    needs: job1
    
    steps:
      - uses: actions/checkout@v3
          
      - name: Upload Artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ./build

      - run: ls build





          
          
